[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
addopts = "--doctest-modules --cov= --cov-report=term-missing"
python_files = "test_*.py"  # Adiciona esta linha


[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
lint = "black --check --diff . && isort --check --diff ."
correct = "black . && isort ."
test = "pytest -s -x --cov=. -vv"
post_test = "coverage html"
