"""Create text-messagens

Revision ID: f16ed8f7b77e
Revises: 3b2b10d59d69
Create Date: 2025-02-14 13:59:51.612672

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f16ed8f7b77e"
down_revision: Union[str, None] = "3b2b10d59d69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
