"""ReaviewMessage

Revision ID: 22f5c741bba2
Revises: f16ed8f7b77e
Create Date: 2025-02-14 14:00:58.441361

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22f5c741bba2"
down_revision: Union[str, None] = "f16ed8f7b77e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
