"""adicioando base sqlalquimist

Revision ID: 622c984f5e9b
Revises: a1bf993184b8
Create Date: 2025-02-14 19:10:33.353219

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "622c984f5e9b"
down_revision: Union[str, None] = "a1bf993184b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
