"""Create Category

Revision ID: a1bf993184b8
Revises: 22f5c741bba2
Create Date: 2025-02-14 14:37:27.420170

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1bf993184b8"
down_revision: Union[str, None] = "22f5c741bba2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("category", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "category")
    # ### end Alembic commands ###
